/**
 * YouTube adapter — playlist + transcript harvesting for personality-disorders corpus
 * Uses YOUTUBE_API_KEY if present (Data API v3), else falls back to scraping + youtube-transcript
 */

export interface YouTubeVideo {
  videoId: string;
  title: string;
  channelTitle?: string;
  publishedAt?: string;
  duration?: string;
  url: string;
}

export interface TranscriptResult {
  videoId: string;
  transcript: string;
  wordCount: number;
  coverage: number; // 0-1, ratio of transcript length vs expected (duration * ~150 wpm)
  isAutoGenerated: boolean;
  language?: string;
  error?: string;
}

export function parsePlaylistId(url: string): string | null {
  try {
    const u = new URL(url);
    const list = u.searchParams.get("list");
    if (list) return list;
    // youtu.be/xxx?si=... with list param already handled
    return null;
  } catch {
    const m = url.match(/[?&]list=([^&]+)/);
    return m ? m[1] : null;
  }
}

export function parseVideoId(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.hostname === "youtu.be") return u.pathname.slice(1).split("?")[0].split("/")[0] || null;
    const v = u.searchParams.get("v");
    if (v) return v;
    const m = url.match(/\/embed\/([^?/]+)/);
    if (m) return m[1];
    return null;
  } catch {
    return null;
  }
}

export async function listPlaylistVideos(playlistId: string, max = 25): Promise<YouTubeVideo[]> {
  const apiKey = (process.env.YOUTUBE_API_KEY || process.env.YOUTUBE_CLIENT_ID || "").trim(); // allow API key via YOUTUBE_API_KEY
  // If no API key, try scraping the playlist page for videoIds (light fallback)
  if (!apiKey || apiKey.length < 20 || apiKey.includes("apps.googleusercontent")) {
    return scrapePlaylistVideos(playlistId, max);
  }
  const videos: YouTubeVideo[] = [];
  let pageToken = "";
  try {
    while (videos.length < max) {
      const url = `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,contentDetails&playlistId=${playlistId}&maxResults=${Math.min(50, max - videos.length)}&key=${apiKey}${pageToken ? `&pageToken=${pageToken}` : ""}`;
      const controller = new AbortController();
      const t = setTimeout(() => controller.abort(), 8000);
      const res = await fetch(url, { signal: controller.signal });
      clearTimeout(t);
      if (!res.ok) throw new Error(`YouTube API ${res.status}`);
      const data: any = await res.json();
      for (const item of data.items || []) {
        const vid = item.contentDetails?.videoId || item.snippet?.resourceId?.videoId;
        if (!vid) continue;
        videos.push({
          videoId: vid,
          title: item.snippet?.title || vid,
          channelTitle: item.snippet?.channelTitle,
          publishedAt: item.snippet?.publishedAt,
          url: `https://www.youtube.com/watch?v=${vid}`,
        });
        if (videos.length >= max) break;
      }
      if (!data.nextPageToken) break;
      pageToken = data.nextPageToken;
    }
  } catch (e) {
    // Fallback to scraping on API failure
    if (videos.length === 0) return scrapePlaylistVideos(playlistId, max);
  }
  return videos.slice(0, max);
}

async function scrapePlaylistVideos(playlistId: string, max: number): Promise<YouTubeVideo[]> {
  try {
    const url = `https://www.youtube.com/playlist?list=${playlistId}`;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0 manifesto-research/0.1" }, signal: controller.signal });
    clearTimeout(t);
    if (!res.ok) return [];
    const html = await res.text();
    // Extract videoIds from playlist HTML: "videoId":"<id>"
    const ids = [...new Set([...html.matchAll(/"videoId":"([^"]+)"/g)].map(m => m[1]))].slice(0, max);
    // Try to get titles
    const titles = [...html.matchAll(/"title":\{"runs":\[\{"text":"([^"]+)"\}/g)].map(m => m[1]);
    return ids.map((id, i) => ({
      videoId: id,
      title: titles[i] ? decodeHtml(titles[i]) : id,
      url: `https://www.youtube.com/watch?v=${id}`,
    }));
  } catch {
    return [];
  }
}

function decodeHtml(s: string): string {
  return s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
}

export async function fetchTranscript(videoId: string): Promise<TranscriptResult> {
  // Try youtube-transcript package if available (optional dep)
  try {
    // Dynamic import to avoid hard dep
    const mod: any = await import("youtube-transcript" as any).catch(() => null);
    if (mod?.YoutubeTranscript) {
      const transcript = await mod.YoutubeTranscript.fetchTranscript(videoId);
      const text = transcript.map((x: any) => x.text).join(" ").replace(/\s+/g, " ").trim();
      const wordCount = text.split(/\s+/).filter(Boolean).length;
      // coverage heuristic: wordCount / (duration estimate 10min *150wpm =1500) -> cap 1
      const coverage = Math.min(1, wordCount / 800);
      return { videoId, transcript: text.slice(0, 15000), wordCount, coverage, isAutoGenerated: transcript[0]?.isAutoGenerated ?? true };
    }
  } catch {}

  // Fallback 1: youtubetranscript.com
  try {
    const url = `https://youtubetranscript.com/?server_vid=${videoId}`;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" }, signal: controller.signal });
    clearTimeout(t);
    if (res.ok) {
      const html = await res.text();
      const m = html.match(/<transcript[^>]*>([\s\S]*?)<\/transcript>/i);
      if (m) {
        const text = m[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 15000);
        const wordCount = text.split(/\s+/).filter(Boolean).length;
        if (wordCount > 50) return { videoId, transcript: text, wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: true };
      }
    }
  } catch {}

  // Fallback 2: timedtext API (scrape video page for captionTracks)
  try {
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(watchUrl, { headers: { "User-Agent": "Mozilla/5.0" }, signal: controller.signal });
    clearTimeout(t);
    if (res.ok) {
      const html = await res.text();
      const m = html.match(/"captionTracks":(\[.*?\])/);
      if (m) {
        const tracks = JSON.parse(m[1]);
        const track = tracks.find((x: any) => x.languageCode === "en") || tracks[0];
        if (track?.baseUrl) {
          const capRes = await fetch(track.baseUrl);
          if (capRes.ok) {
            const xml = await capRes.text();
            const segs = [...xml.matchAll(/<text[^>]*>([^<]+)<\/text>/g)].map(x => decodeHtml(x[1]));
            const text = segs.join(" ").replace(/\s+/g, " ").trim().slice(0, 15000);
            const wordCount = text.split(/\s+/).filter(Boolean).length;
            if (wordCount > 50) return { videoId, transcript: text, wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: track.kind === "asr" };
          }
        }
      }
    }
  } catch {}

  return { videoId, transcript: "", wordCount: 0, coverage: 0, isAutoGenerated: true, error: "no transcript" };
}

export async function harvestYouTubePlaylists(urls: string[], idea: string, maxVideos = 25): Promise<any[]> {
  const assets: any[] = [];
  const allVideoIds = new Set<string>();
  for (const u of urls) {
    const pid = parsePlaylistId(u);
    const vid = parseVideoId(u);
    if (pid) {
      const vids = await listPlaylistVideos(pid, maxVideos);
      for (const v of vids) {
        if (allVideoIds.has(v.videoId)) continue;
        allVideoIds.add(v.videoId);
        // Will fetch transcript later
      }
    } else if (vid) {
      allVideoIds.add(vid);
    }
  }
  // For 25-min workflow, cap total videos
  const videoList = [...allVideoIds].slice(0, maxVideos);
  // Fetch transcripts in parallel, limited concurrency
  const transcriptResults: TranscriptResult[] = [];
  for (const vid of videoList) {
    const tr = await fetchTranscript(vid);
    transcriptResults.push(tr);
    // Small delay to respect rate limits
    await new Promise(r => setTimeout(r, 300));
  }
  for (const tr of transcriptResults) {
    if (!tr.transcript || tr.wordCount < 80) continue;
    assets.push({
      assetId: `yt_${tr.videoId}`,
      sourceUrl: `https://www.youtube.com/watch?v=${tr.videoId}`,
      title: `YouTube Transcript — ${tr.videoId} — ${idea.slice(0, 40)}`,
      snippet: tr.transcript.slice(0, 300),
      domain: "youtube.com",
      score: 0,
      relevanceScore: 0,
      evidence: [`transcript ${tr.wordCount} words, coverage ${tr.coverage.toFixed(2)}`],
      contentPreview: tr.transcript.slice(0, 800),
      rightsClassification: "REFERENCE_ONLY",
      rightsConfidence: 0.3,
      category: "transcript",
      transcript: tr.transcript,
      wordCount: tr.wordCount,
      coverage: tr.coverage,
      isAutoGenerated: tr.isAutoGenerated,
    });
  }
  return assets;
}
