/**
 * YouTube-DLP adapter — yt-dlp powered replacement for youtube.ts
 * Primary: yt-dlp binary (brew/pip) for playlist enumeration + transcript extraction
 * Fallback: legacy scraping / API logic if yt-dlp unavailable or fails
 *
 * Drop-in replacement: same exports as youtube.ts
 *   parsePlaylistId, parseVideoId, listPlaylistVideos, fetchTranscript, harvestYouTubePlaylists
 *
 * Requires: yt-dlp binary in PATH or python -m yt_dlp, ffmpeg, optional deno/node for yt-dlp-ejs
 * Install: brew install yt-dlp ffmpeg  OR  pipx install yt-dlp  OR  pip install "yt-dlp[default]"
 */

import { spawn } from "child_process";
import { existsSync, readdirSync, readFileSync, mkdirSync, mkdtempSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";

// Reuse parse helpers from legacy (keep identical signature for drop-in)
export function parsePlaylistId(url: string): string | null {
  try {
    const u = new URL(url);
    const list = u.searchParams.get("list");
    if (list) return list;
    return null;
  } catch {
    const m = url.match(/[?&]list=([^&]+)/);
    return m ? m[1] : null;
  }
}

export function parseVideoId(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.hostname === "youtu.be") return u.pathname.slice(1).split("?")[0].split("/")[0] || null;
    const v = u.searchParams.get("v");
    if (v) return v;
    const m = url.match(/\/embed\/([^?/]+)/);
    if (m) return m[1];
    return null;
  } catch {
    return null;
  }
}

export interface YouTubeVideo {
  videoId: string;
  title: string;
  channelTitle?: string;
  publishedAt?: string;
  duration?: string;
  url: string;
}

export interface TranscriptResult {
  videoId: string;
  transcript: string;
  wordCount: number;
  coverage: number;
  isAutoGenerated: boolean;
  language?: string;
  error?: string;
}

// ---------- yt-dlp helpers ----------

async function whichYtDlp(): Promise<string[] | null> {
  // Try `yt-dlp` binary first, then `python3 -m yt_dlp`
  for (const cmd of [["yt-dlp"], ["python3", "-m", "yt_dlp"]]) {
    try {
      const ok = await execCmd(cmd[0], [...cmd.slice(1), "--version"], 5000);
      if (ok.code === 0 && ok.stdout.trim().match(/^\d{4}\./)) return cmd;
    } catch {}
  }
  return null;
}

interface ExecResult { code: number; stdout: string; stderr: string; }

function execCmd(cmd: string, args: string[], timeoutMs = 30000): Promise<ExecResult> {
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let timedOut = false;
    const child = spawn(cmd, args, { stdio: ["ignore", "pipe", "pipe"] });
    const t = setTimeout(() => {
      timedOut = true;
      try { child.kill("SIGKILL"); } catch {}
      resolve({ code: 124, stdout, stderr: stderr + "\n[TIMEOUT]" });
    }, timeoutMs);
    // Don't keep process alive just for timer if child exits early
    (t as any)?.unref?.();
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("close", (code) => {
      clearTimeout(t);
      if (timedOut) return;
      resolve({ code: code ?? 1, stdout, stderr });
    });
    child.on("error", (e: any) => {
      clearTimeout(t);
      resolve({ code: 127, stdout, stderr: stderr + String(e.message) });
    });
  });
}

function decodeHtml(s: string): string {
  return s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
}

// ---------- yt-dlp: list playlist ----------

async function listPlaylistVideosViaYtDlp(playlistId: string, max: number, ytCmd: string[]): Promise<YouTubeVideo[]> {
  // Use --flat-playlist --dump-single-json to avoid downloading. Works for both playlist and channel.
  const playlistUrl = `https://www.youtube.com/playlist?list=${playlistId}`;
  // yt-dlp args: flat, json, no warnings, socket-timeout 8s, ignore errors
  const args = [
    ...ytCmd.slice(1),
    "--flat-playlist",
    "--dump-single-json",
    "--no-warnings",
    "--ignore-errors",
    "--socket-timeout", "8",
    "--extractor-args", "youtube:player_client=android",
    playlistUrl,
  ];
  const res = await execCmd(ytCmd[0], args, 20000);
  if (res.code !== 0 || !res.stdout.trim()) {
    throw new Error(`yt-dlp playlist failed code=${res.code} stderr=${res.stderr.slice(0, 400)}`);
  }
  let data: any;
  try {
    data = JSON.parse(res.stdout);
  } catch (e) {
    throw new Error(`yt-dlp playlist JSON parse fail: ${String(e).slice(0, 200)}`);
  }
  const entries: any[] = Array.isArray(data.entries) ? data.entries : Array.isArray(data) ? data : [];
  const videos: YouTubeVideo[] = [];
  for (const e of entries.slice(0, max)) {
    const vid = e.id || e.url?.match(/v=([^&]+)/)?.[1];
    if (!vid || vid.length < 5) continue;
    videos.push({
      videoId: vid,
      title: e.title || vid,
      channelTitle: e.channel || e.uploader || e.channelTitle,
      publishedAt: e.upload_date ? `${e.upload_date.slice(0,4)}-${e.upload_date.slice(4,6)}-${e.upload_date.slice(6,8)}` : undefined,
      duration: e.duration ? String(e.duration) : undefined,
      url: e.url?.startsWith("http") ? e.url : `https://www.youtube.com/watch?v=${vid}`,
    });
  }
  return videos;
}

// ---------- legacy fallback (scrape) — mirrors youtube.ts ----------
async function scrapePlaylistVideos(playlistId: string, max: number): Promise<YouTubeVideo[]> {
  try {
    const url = `https://www.youtube.com/playlist?list=${playlistId}`;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0 manifesto-research/0.1" }, signal: controller.signal });
    clearTimeout(t);
    if (!res.ok) return [];
    const html = await res.text();
    const ids = [...new Set([...html.matchAll(/"videoId":"([^"]+)"/g)].map((m) => m[1]))].slice(0, max);
    const titles = [...html.matchAll(/"title":\{"runs":\[\{"text":"([^"]+)"\}/g)].map((m) => m[1]);
    return ids.map((id, i) => ({
      videoId: id,
      title: titles[i] ? decodeHtml(titles[i]) : id,
      url: `https://www.youtube.com/watch?v=${id}`,
    }));
  } catch {
    return [];
  }
}

async function listPlaylistVideosViaApi(playlistId: string, max: number): Promise<YouTubeVideo[]> {
  const apiKey = (process.env.YOUTUBE_API_KEY || "").trim();
  if (!apiKey || apiKey.length < 20 || apiKey.includes("apps.googleusercontent")) return scrapePlaylistVideos(playlistId, max);
  const videos: YouTubeVideo[] = [];
  let pageToken = "";
  try {
    while (videos.length < max) {
      const url = `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,contentDetails&playlistId=${playlistId}&maxResults=${Math.min(50, max - videos.length)}&key=${apiKey}${pageToken ? `&pageToken=${pageToken}` : ""}`;
      const controller = new AbortController();
      const t = setTimeout(() => controller.abort(), 8000);
      const res = await fetch(url, { signal: controller.signal });
      clearTimeout(t);
      if (!res.ok) throw new Error(`YouTube API ${res.status}`);
      const data: any = await res.json();
      for (const item of data.items || []) {
        const vid = item.contentDetails?.videoId || item.snippet?.resourceId?.videoId;
        if (!vid) continue;
        videos.push({ videoId: vid, title: item.snippet?.title || vid, channelTitle: item.snippet?.channelTitle, publishedAt: item.snippet?.publishedAt, url: `https://www.youtube.com/watch?v=${vid}` });
        if (videos.length >= max) break;
      }
      if (!data.nextPageToken) break;
      pageToken = data.nextPageToken;
    }
  } catch {
    if (videos.length === 0) return scrapePlaylistVideos(playlistId, max);
  }
  return videos.slice(0, max);
}

export async function listPlaylistVideos(playlistId: string, max = 25): Promise<YouTubeVideo[]> {
  // Prefer yt-dlp, fallback to API/scrape
  const ytCmd = await whichYtDlp();
  if (ytCmd) {
    try {
      const vids = await listPlaylistVideosViaYtDlp(playlistId, max, ytCmd);
      if (vids.length > 0) {
        console.log(`[youtube-dlp] playlist ${playlistId.slice(0, 8)}… → ${vids.length} via yt-dlp`);
        return vids;
      }
    } catch (e: any) {
      console.log(`[youtube-dlp] playlist fallback (yt-dlp fail: ${String(e.message).slice(0, 120)}), trying API/scrape`);
    }
  } else {
    console.log(`[youtube-dlp] yt-dlp not found, using API/scrape fallback`);
  }
  return listPlaylistVideosViaApi(playlistId, max);
}

// ---------- yt-dlp: fetch transcript ----------

function parseJson3File(path: string): { text: string; isAuto: boolean } | null {
  try {
    const raw = readFileSync(path, "utf-8");
    const data = JSON.parse(raw);
    const events: any[] = data.events || [];
    const segs: string[] = [];
    for (const ev of events) {
      if (!ev.segs) continue;
      for (const s of ev.segs) {
        if (s.utf8) segs.push(s.utf8);
      }
    }
    const text = segs.join("").replace(/\n/g, " ").replace(/\s+/g, " ").trim();
    // json3 from auto subs often has no explicit flag; treat as auto if filename contains .auto or if no manual counterpart existed
    const isAuto = path.includes(".auto") || path.includes(".json3");
    return text.length > 20 ? { text, isAuto } : null;
  } catch {
    return null;
  }
}

function parseVttFile(path: string): { text: string } | null {
  try {
    const raw = readFileSync(path, "utf-8");
    // Strip WEBVTT header, timestamps, cues
    const lines = raw.split("\n");
    const txt: string[] = [];
    for (const l of lines) {
      const t = l.trim();
      if (!t) continue;
      if (t.startsWith("WEBVTT")) continue;
      if (t.startsWith("NOTE")) continue;
      if (/^\d{2}:\d{2}:\d{2}\.\d{3} -->/.test(t)) continue;
      if (/^\d+$/.test(t)) continue;
      // Remove inline tags <c>, <00:00:01.000>
      txt.push(t.replace(/<[^>]+>/g, "").trim());
    }
    const text = txt.join(" ").replace(/\s+/g, " ").trim();
    return text.length > 20 ? { text } : null;
  } catch {
    return null;
  }
}

async function fetchTranscriptViaYtDlp(videoId: string, ytCmd: string[]): Promise<TranscriptResult | null> {
  const tmp = mkdtempSync(join(tmpdir(), "ytdlp-"));
  try {
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const outTpl = join(tmp, "%(id)s.%(ext)s");
    // Try json3 first (structured), then vtt/srt fallback. yt-dlp will skip download.
    // --write-auto-subs covers auto captions; --write-sub covers manual.
    const args = [
      ...ytCmd.slice(1),
      "--write-auto-subs",
      "--write-subs",
      "--sub-langs", "en.*,en",
      "--sub-format", "json3/srt/vtt/best",
      "--skip-download",
      "--no-warnings",
      "--ignore-errors",
      "--socket-timeout", "8",
      "--extractor-args", "youtube:player_client=android",
      "-o", outTpl,
      videoUrl,
    ];
    const res = await execCmd(ytCmd[0], args, 25000);
    // Even if code !=0, sub files may have been written (some videos have no subs)
    const files = existsSync(tmp) ? readdirSync(tmp) : [];
    // Prefer json3, then srt, then vtt
    let chosen: string | null = null;
    // json3 files: <id>.en.json3 or <id>.en-orig.json3 or .en-auto
    const json3 = files.filter((f) => f.endsWith(".json3"));
    const srt = files.filter((f) => f.endsWith(".srt"));
    const vtt = files.filter((f) => f.endsWith(".vtt"));
    if (json3.length > 0) {
      // Prefer non-auto (manual) if present, else first
      const manual = json3.find((f) => !f.includes("auto") && f.includes(".en."));
      chosen = join(tmp, manual || json3[0]);
      const parsed = parseJson3File(chosen);
      if (parsed && parsed.text.length > 50) {
        const wordCount = parsed.text.split(/\s+/).filter(Boolean).length;
        return {
          videoId,
          transcript: parsed.text.slice(0, 15000),
          wordCount,
          coverage: Math.min(1, wordCount / 800),
          isAutoGenerated: parsed.isAuto,
          language: "en",
        };
      }
    }
    if (srt.length > 0) {
      chosen = join(tmp, srt[0]);
      const parsed = parseVttFile(chosen);
      if (parsed && parsed.text.length > 50) {
        const wordCount = parsed.text.split(/\s+/).filter(Boolean).length;
        return { videoId, transcript: parsed.text.slice(0, 15000), wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: true, language: "en" };
      }
    }
    if (vtt.length > 0) {
      chosen = join(tmp, vtt[0]);
      const parsed = parseVttFile(chosen);
      if (parsed && parsed.text.length > 50) {
        const wordCount = parsed.text.split(/\s+/).filter(Boolean).length;
        return { videoId, transcript: parsed.text.slice(0, 15000), wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: true, language: "en" };
      }
    }
    // No subs found
    if (res.stderr.slice(0, 500).includes("no subtitles")) return null;
    return null;
  } finally {
    try { rmSync(tmp, { recursive: true, force: true }); } catch {}
  }
}

// ---------- legacy transcript fallbacks (mirror youtube.ts) ----------

async function fetchTranscriptLegacy(videoId: string): Promise<TranscriptResult> {
  try {
    const mod: any = await import("youtube-transcript" as any).catch(() => null);
    if (mod?.YoutubeTranscript) {
      const transcript = await mod.YoutubeTranscript.fetchTranscript(videoId);
      const text = transcript.map((x: any) => x.text).join(" ").replace(/\s+/g, " ").trim();
      const wordCount = text.split(/\s+/).filter(Boolean).length;
      return { videoId, transcript: text.slice(0, 15000), wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: transcript[0]?.isAutoGenerated ?? true };
    }
  } catch {}
  try {
    const url = `https://youtubetranscript.com/?server_vid=${videoId}`;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" }, signal: controller.signal });
    clearTimeout(t);
    if (res.ok) {
      const html = await res.text();
      const m = html.match(/<transcript[^>]*>([\s\S]*?)<\/transcript>/i);
      if (m) {
        const text = m[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 15000);
        const wordCount = text.split(/\s+/).filter(Boolean).length;
        if (wordCount > 50) return { videoId, transcript: text, wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: true };
      }
    }
  } catch {}
  try {
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(watchUrl, { headers: { "User-Agent": "Mozilla/5.0" }, signal: controller.signal });
    clearTimeout(t);
    if (res.ok) {
      const html = await res.text();
      const m = html.match(/"captionTracks":(\[.*?\])/);
      if (m) {
        const tracks = JSON.parse(m[1]);
        const track = tracks.find((x: any) => x.languageCode === "en") || tracks[0];
        if (track?.baseUrl) {
          const capRes = await fetch(track.baseUrl);
          if (capRes.ok) {
            const xml = await capRes.text();
            const segs = [...xml.matchAll(/<text[^>]*>([^<]+)<\/text>/g)].map((x) => decodeHtml(x[1]));
            const text = segs.join(" ").replace(/\s+/g, " ").trim().slice(0, 15000);
            const wordCount = text.split(/\s+/).filter(Boolean).length;
            if (wordCount > 50) return { videoId, transcript: text, wordCount, coverage: Math.min(1, wordCount / 800), isAutoGenerated: track.kind === "asr" };
          }
        }
      }
    }
  } catch {}
  return { videoId, transcript: "", wordCount: 0, coverage: 0, isAutoGenerated: true, error: "no transcript" };
}

export async function fetchTranscript(videoId: string): Promise<TranscriptResult> {
  const ytCmd = await whichYtDlp();
  if (ytCmd) {
    try {
      const res = await fetchTranscriptViaYtDlp(videoId, ytCmd);
      if (res && res.wordCount >= 50) {
        console.log(`[youtube-dlp] transcript ${videoId} → ${res.wordCount}w via yt-dlp`);
        return res;
      }
      console.log(`[youtube-dlp] yt-dlp no transcript for ${videoId}, falling back to legacy`);
    } catch (e: any) {
      console.log(`[youtube-dlp] yt-dlp transcript fail ${videoId}: ${String(e.message).slice(0, 120)}`);
    }
  }
  return fetchTranscriptLegacy(videoId);
}

// ---------- harvest ----------

export async function harvestYouTubePlaylists(urls: string[], idea: string, maxVideos = 25): Promise<any[]> {
  const assets: any[] = [];
  const allVideoIds = new Set<string>();

  // 1. Enumerate all videos from playlists + singletons
  for (const u of urls) {
    const pid = parsePlaylistId(u);
    const vid = parseVideoId(u);
    if (pid) {
      const vids = await listPlaylistVideos(pid, Math.min(maxVideos, 50));
      for (const v of vids) {
        if (allVideoIds.has(v.videoId)) continue;
        allVideoIds.add(v.videoId);
        // stash title metadata for later use
        // we could map videoId->title but keep simple: harvest loop will refetch title if needed
      }
    } else if (vid) {
      allVideoIds.add(vid);
    } else if (u.includes("youtube.com") || u.includes("youtu.be")) {
      // Bare channel or unknown youtube URL — try yt-dlp flat on the URL itself
      const ytCmd = await whichYtDlp();
      if (ytCmd) {
        try {
          const args = [...ytCmd.slice(1), "--flat-playlist", "--dump-single-json", "--no-warnings", "--ignore-errors", "--socket-timeout", "8", u];
          const res = await execCmd(ytCmd[0], args, 15000);
          if (res.code === 0) {
            const data: any = JSON.parse(res.stdout);
            const entries: any[] = Array.isArray(data.entries) ? data.entries : data.id ? [data] : [];
            for (const e of entries.slice(0, 5)) {
              const id = e.id || parseVideoId(e.url || "");
              if (id) allVideoIds.add(id);
            }
          }
        } catch {}
      }
    }
  }

  const videoList = [...allVideoIds].slice(0, maxVideos);
  if (videoList.length === 0) {
    console.log(`[youtube-dlp] no videos enumerated from ${urls.length} URLs`);
    return [];
  }
  console.log(`[youtube-dlp] enumerated ${videoList.length} unique videos from ${urls.length} playlists, idea="${idea.slice(0, 40)}"`);

  // 2. Fetch transcripts with limited concurrency (3 at a time to avoid rate-limit)
  const transcriptResults: TranscriptResult[] = [];
  const concurrency = 3;
  for (let i = 0; i < videoList.length; i += concurrency) {
    const batch = videoList.slice(i, i + concurrency);
    const results = await Promise.all(batch.map((vid) => fetchTranscript(vid)));
    transcriptResults.push(...results);
    // gentle rate-limit between batches
    if (i + concurrency < videoList.length) await new Promise((r) => setTimeout(r, 600));
  }

  // 3. Map to assets (same shape as legacy youtube.ts so pipeline/verification unchanged)
  for (const tr of transcriptResults) {
    if (!tr.transcript || tr.wordCount < 80) {
      if (tr.error) console.log(`[youtube-dlp] skip ${tr.videoId}: ${tr.error} (${tr.wordCount}w)`);
      continue;
    }
    assets.push({
      assetId: `yt_${tr.videoId}`,
      sourceUrl: `https://www.youtube.com/watch?v=${tr.videoId}`,
      title: `YouTube Transcript — ${tr.videoId} — ${idea.slice(0, 40)}`,
      snippet: tr.transcript.slice(0, 300),
      domain: "youtube.com",
      score: 0,
      relevanceScore: 0,
      evidence: [`transcript ${tr.wordCount} words, coverage ${tr.coverage.toFixed(2)}${tr.isAutoGenerated ? " (auto)" : " (manual)"} via yt-dlp`],
      contentPreview: tr.transcript.slice(0, 800),
      rightsClassification: "REFERENCE_ONLY",
      rightsConfidence: 0.3,
      category: "transcript",
      transcript: tr.transcript,
      wordCount: tr.wordCount,
      coverage: tr.coverage,
      isAutoGenerated: tr.isAutoGenerated,
    });
  }
  console.log(`[youtube-dlp] → ${assets.length}/${videoList.length} usable transcripts (≥80w)`);
  return assets;
}

// Also export helpers for testing
export const _internal = { whichYtDlp, execCmd, fetchTranscriptViaYtDlp, listPlaylistVideosViaYtDlp };
