console.log("test start");
console.log("importing createHash");
import { createHash } from "crypto";
console.log("imported crypto");
import { join } from "path";
console.log("imported path");
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
console.log("imported fs");
import { RESEARCH_CONFIG } from "./src/research/config.js";
console.log("imported config");
import { runResearchOneShot, generateOneShotQueries } from "./src/research/pipeline.js";
console.log("imported pipeline");
import { harvestYouTubePlaylists } from "./src/research/adapters/youtube.js";
console.log("imported youtube");
import { harvestMessageBoards } from "./src/research/adapters/messageBoard.js";
console.log("imported board");
import { verifyAll } from "./src/research/verification.js";
console.log("imported verify");
import { writeHyperfixation, writeResearchLog } from "./src/research/vaultWriter.js";
console.log("imported vaultWriter - done");
